### ISSUE TITLE
LISDKAuthError Code 6

### ISSUE THREAD

**Issue by thijsalbers** [EveryUP/ti.linkedin#1]
Thank you for what seems to be a great module. I'm trying to implement it on iOS, Ti SDK 7.1.1.

However, whatever I seem to try, I'm always getting the 'Download LinkedIn App' alertdialog. Somehow it seems to not find the LinkedIn app on the phone. I've included all the necessary information in tiapp.xml and added the bundle id etc. to the LinkedIn app iOS settings.

Any suggestion what to try next?

`{"success":false,"code":6,"error":"Error Domain=LISDKAuthError Code=6 \"(null)\" UserInfo={You need to download the LinkedIn App in order to connect with LinkedIn=info}","canceled":false,"bubbles":true,"type":"login","source":{},"cancelBubble":false}`

**Comment by AndreaVitale** [comment]
Hi, have you got it working? Is working for us on two app.
